
tasks:
  - init: Installing Rust
    command: rustup default nightly-2024-01-20
  - init: Downloading Rust standard library
    command: rustup component add rust-src --toolchain nightly-2024-01-20-x86_64-unknown-linux-gnu
  - init: Compiling xFetch
    command: RUSTFLAGS="-Zlocation-detail=none" cargo build --target x86_64-unknown-linux-gnu --profile optimized-build -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort
  - init: Running xFetch
    command: ./target/x86_64-unknown-linux-gnu/optimized-build/xfetch

