[package]
name = "xfetch"
version = "1.0.0"
edition = "2021"

[dependencies]
colored = "2.1.0"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.optimized-build]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"
strip = true
