name: xFetchCompile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Installing Rust (nightly)
      uses: actions-rs/toolchain@v1
      with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy

    - name: Compiling xFetch
      run: RUSTFLAGS="-Zlocation-detail=none" cargo build --target x86_64-unknown-linux-gnu --profile optimized-build -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort
    - name: Running Tests
      run: cargo test --verbose
